# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StylingRequestViewTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DLRadioButton', '~> 1.4'
	pod 'BEMCheckBox'

  # Pods for StylingRequestViewTest

  target 'StylingRequestViewTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StylingRequestViewTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
