# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Pattern_Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_Pattern_Test
	pod 'SwiftEventBus', :tag => '2.2.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
	pod 'ObjectMapper'
	pod 'Kingfisher'
	pod 'Alamofire'
	pod 'RxSwift',    '~> 3.0'
	pod 'RxCocoa',    '~> 3.0'

  target 'MVVM_Pattern_TestTests' do
    inherit! :search_paths
    # Pods for testing
		pod 'RxSwift',    '~> 3.0'
		pod 'RxCocoa',    '~> 3.0'
  end

  target 'MVVM_Pattern_TestUITests' do
    inherit! :search_paths
    # Pods for testing
		pod 'RxSwift',    '~> 3.0'
		pod 'RxCocoa',    '~> 3.0'
  end

end
